-- Start Update

-- Version 2

-- Version 3
ALTER TABLE albums ADD COLUMN rating_web DOUBLE DEFAULT 0.0;
ALTER TABLE albums ADD COLUMN rating_own DOUBLE DEFAULT 0.0;
ALTER TABLE albums ADD COLUMN rating_note TEXT;

ALTER TABLE songs ADD COLUMN rating_web DOUBLE DEFAULT 0.0;
ALTER TABLE songs ADD COLUMN rating_own DOUBLE DEFAULT 0.0;
ALTER TABLE songs ADD COLUMN rating_note TEXT;

ALTER TABLE movies ADD COLUMN rating_web DOUBLE DEFAULT 0.0;
ALTER TABLE movies ADD COLUMN rating_own DOUBLE DEFAULT 0.0;
ALTER TABLE movies ADD COLUMN rating_note TEXT;

ALTER TABLE games ADD COLUMN rating_web DOUBLE DEFAULT 0.0;
ALTER TABLE games ADD COLUMN rating_own DOUBLE DEFAULT 0.0;
ALTER TABLE games ADD COLUMN rating_note TEXT;

ALTER TABLE books ADD COLUMN rating_web DOUBLE DEFAULT 0.0;
ALTER TABLE books ADD COLUMN rating_own DOUBLE DEFAULT 0.0;
ALTER TABLE books ADD COLUMN rating_note TEXT;

-- Version 4
ALTER TABLE albums ADD COLUMN last_heard DATE DEFAULT NULL;
ALTER TABLE movies ADD COLUMN last_seen DATE DEFAULT NULL;
ALTER TABLE games ADD COLUMN last_played DATE DEFAULT NULL;
ALTER TABLE books ADD COLUMN last_read DATE DEFAULT NULL;

-- Version 5
ALTER TABLE filters ADD COLUMN customFields VARCHAR(255) DEFAULT '';

-- End Update